In [1]:
import pandas as pd

### Merging Two DataFrames

In [2]:
# Definition:
# Merge two DataFrames based on a common column.
# Functions used for combining DataFrames:
# merge()  → Combine based on a common column
# join()   → Combine based on index
# concat() → Combine DataFrames row-wise or column-wise
# Important points:
# on      → Specifies the common column used for merging
# how     → Specifies the type of join
# inner   → Returns only matching records
# left    → Returns all records from the left DataFrame
# right   → Returns all records from the right DataFrame
# outer   → Returns all records from both DataFrames
# axis=0  → Combine DataFrames row-wise
# axis=1  → Combine DataFrames column-wise
# suffixes → Handles same column names in both DataFrames

###### Creating Two DataFrames for merge()

In [3]:
# merge() function

# Create the first DataFrame
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'DreamCompany': ["Google", "Nvidia", "Accenture"]
})

# Create the second DataFrame
df2 = pd.DataFrame({
    'ID': [2, 3, 4],
    'DreamPackage': [20, 24, 50]
})

# Display both DataFrames
print(df1)
print(df2)

   ID DreamCompany
0   1       Google
1   2       Nvidia
2   3    Accenture
   ID  DreamPackage
0   2            20
1   3            24
2   4            50

###### Inner Merge Using merge()

In [4]:
# merge() function behaves like joins in SQL
# By default, merge() performs an inner join
# Inner merge: Returns common records from both DataFrames

merge_df = pd.merge(df1, df2, on="ID")

merge_df

   ID DreamCompany  DreamPackage
0   2       Nvidia            20
1   3    Accenture            24

###### Adding a New Column Before Merging DataFrames

In [5]:
# Add a new column "Role" to df1
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'DreamCompany': ["Google", "Nvidia", "Accenture"],
    'Role': ["DA", "DS", "HR"]
})

# Create the second DataFrame
df2 = pd.DataFrame({
    'ID': [2, 3, 4],
    'DreamPackage': [20, 24, 50]
})

# Display both DataFrames
print(df1)
print(df2)

   ID DreamCompany Role
0   1       Google   DA
1   2       Nvidia   DS
2   3    Accenture   HR
   ID  DreamPackage
0   2            20
1   3            24
2   4            50

###### Performing an Inner Merge Using merge()

In [6]:
# Inner merge: Common records from both DataFrames
# Main point:
# inner merge returns only matching/common records
# from both DataFrames based on the common column.
merge_df = pd.merge(df1, df2, on="ID", how="inner")

merge_df

   ID DreamCompany Role  DreamPackage
0   2       Nvidia   DS            20
1   3    Accenture   HR            24

###### Left Merge

In [7]:
# Left merge: Keep all records from the left DataFrame
# and matching records from the right DataFrame
# left → all records from LEFT + matching records from RIGHT
merge_df = pd.merge(df1, df2, on="ID", how="left")

merge_df

   ID DreamCompany Role  DreamPackage
0   1       Google   DA           NaN
1   2       Nvidia   DS          20.0
2   3    Accenture   HR          24.0

###### Right Merge

In [8]:
# Right merge: Keep all records from the right DataFrame
# and matching records from the left DataFrame
# right → all records from RIGHT + matching records from LEFT
merge_df = pd.merge(df1, df2, on="ID", how="right")
merge_df

   ID DreamCompany Role  DreamPackage
0   2       Nvidia   DS            20
1   3    Accenture   HR            24
2   4          NaN  NaN            50

###### Outer Merge

In [9]:
# Outer merge: Keep all records from both DataFrames
# Common records will appear only one time
# outer → all records from LEFT + RIGHT
# common records appear only once
merge_df = pd.merge(df1, df2, on="ID", how="outer")
merge_df

   ID DreamCompany Role  DreamPackage
0   1       Google   DA           NaN
1   2       Nvidia   DS          20.0
2   3    Accenture   HR          24.0
3   4          NaN  NaN          50.0

### join()

In [10]:
# join() : Used to combine DataFrames mainly based on index values.
# Important points:
# join() → combines DataFrames based on index
# By default, join() performs a left join
# It can also perform inner, right, and outer joins
# on parameter → specifies the column to join on
# how parameter → specifies the type of join
# lsuffix → suffix added to overlapping columns from left DataFrame
# rsuffix → suffix added to overlapping columns from right DataFrame
# Useful when DataFrames have the same index

###### Creating a DataFrame with Custom Index Values

In [11]:
df3 = pd.DataFrame(
    {
        "Name_richest": ["Ambani", "Elon", "Niranjan", "Larry"]
    },
    index=[10, 20, 30, 40]
)
df3

   Name_richest
10       Ambani
20         Elon
30     Niranjan
40        Larry

###### Creating a DataFrame with Net Worth and Custom Index

In [12]:
df4 = pd.DataFrame(
    {
        "Networth": [10, 15, 500, 2]
    },
    index=[20, 30, 40, 50]
)
df4

    Networth
20        10
30        15
40       500
50         2

###### Inner Join Using join()

In [13]:
# Inner join: Keep only common index values
# NOte - # inner join → keeps only common index values
# Easy memory: INNER = COMMON ONLY
joined_df = df3.join(df4, how="inner")
joined_df

   Name_richest  Networth
20         Elon        10
30     Niranjan        15
40        Larry       500

###### Left Join Using join()

In [14]:
# Left join: Keep all index values from the left DataFrame
joined_df = df3.join(df4, how="left")
joined_df

   Name_richest  Networth
10       Ambani       NaN
20         Elon      10.0
30     Niranjan      15.0
40        Larry     500.0

###### Right Join Using join()

In [15]:
# Right join: Keep all index values from the right DataFrame
joined_df = df3.join(df4, how="right")
joined_df

   Name_richest  Networth
20         Elon        10
30     Niranjan        15
40        Larry       500
50          NaN         2

###### Outer Join Using join()

In [30]:
# Outer join: Keep all index values from both DataFrames
joined_df = df3.join(df4, how="outer")
joined_df

   Name_richest  Networth
10       Ambani       NaN
20         Elon      10.0
30     Niranjan      15.0
40        Larry     500.0
50          NaN       2.0

### concat()

In [17]:
# Definition:
# concat() is used to combine two or more DataFrames
# row-wise or column-wise.
# axis=0 → Combine rows (vertical)
# axis=1 → Combine columns (horizontal)
# axis=0 → rows are added one below another
# axis=1 → columns are added side by side
# ignore_index=True → creates a new continuous index
# By default, concat() keeps the original index values

###### Concatenating Multiple DataFrames Vertically

In [31]:
df5 = pd.DataFrame({
    "ID": [1, 2],
    "Movie": ["Pappu Power", "Biryani Boss"]
})
df6 = pd.DataFrame({
    "ID": [3, 4],
    "Movie": ["Tea Glass Tiger", "Dosa Don"]
})
df7 = pd.DataFrame({
    "ID": [5, 6],
    "Movie": ["Auto Avengers", "Chai Biscuit Champion"]
})
# Concatenate DataFrames vertically
concat_df = pd.concat(
    [df5, df6, df7],
    axis=0,
    ignore_index=True
)
concat_df

   ID                  Movie
0   1            Pappu Power
1   2           Biryani Boss
2   3        Tea Glass Tiger
3   4               Dosa Don
4   5          Auto Avengers
5   6  Chai Biscuit Champion

## 10. Time Series Operations

In [19]:
# Time Series Operations:
# These operations are performed on date and time data.
# They are used to extract, filter, compare, and analyze dates and times.

1. pd.to_datetime()
Converts a column into datetime format.
2. .dt.year
Extracts the year from a date.
3. .dt.month
Extracts the month from a date.
4. .dt.day
Extracts the day from a date.
5. .dt.day_name()
Returns the name of the day.
6. .dt.month_name()
Returns the name of the month.
7. .dt.dayofweek
Returns the weekday number.
Monday = 0, Sunday = 6
8. .dt.hour
Extracts the hour from datetime.
9. .dt.minute
Extracts the minute from datetime.

###### Creating an Hourly Date Range Using pd.date_range()

In [ ]:
# pd.date_range() → Creates a sequence of dates and times.
# start → Starting date and time.
# end → Ending date and time.
# freq='h' → Generates a date/time value for every hour.

In [32]:
# Create a date range from January 2021 to December 2026
# with an hourly frequency
date_rng = pd.date_range(
    start='2021-01-01',
    end='2026-12-31',
    freq='h'
)
print(date_rng)

DatetimeIndex(['2021-01-01 00:00:00', '2021-01-01 01:00:00',
               '2021-01-01 02:00:00', '2021-01-01 03:00:00',
               '2021-01-01 04:00:00', '2021-01-01 05:00:00',
               '2021-01-01 06:00:00', '2021-01-01 07:00:00',
               '2021-01-01 08:00:00', '2021-01-01 09:00:00',
               ...
               '2026-12-30 15:00:00', '2026-12-30 16:00:00',
               '2026-12-30 17:00:00', '2026-12-30 18:00:00',
               '2026-12-30 19:00:00', '2026-12-30 20:00:00',
               '2026-12-30 21:00:00', '2026-12-30 22:00:00',
               '2026-12-30 23:00:00', '2026-12-31 00:00:00'],
              dtype='datetime64[ns]', length=52561, freq='h')

###### Creating a Monthly Date Range Using pd.date_range()

In [22]:
# pd.date_range() → Creates a sequence of dates.
# start → Starting date.
# end → Ending date.
# freq='ME' → Generates dates at the end of every month.

In [33]:
# Create a date range from January 2021 to December 2026
# with month-end frequency
date_rng = pd.date_range(
    start='2021-01-01',
    end='2026-12-31',
    freq='ME'
)
print(date_rng)

DatetimeIndex(['2021-01-31', '2021-02-28', '2021-03-31', '2021-04-30',
               '2021-05-31', '2021-06-30', '2021-07-31', '2021-08-31',
               '2021-09-30', '2021-10-31', '2021-11-30', '2021-12-31',
               '2022-01-31', '2022-02-28', '2022-03-31', '2022-04-30',
               '2022-05-31', '2022-06-30', '2022-07-31', '2022-08-31',
               '2022-09-30', '2022-10-31', '2022-11-30', '2022-12-31',
               '2023-01-31', '2023-02-28', '2023-03-31', '2023-04-30',
               '2023-05-31', '2023-06-30', '2023-07-31', '2023-08-31',
               '2023-09-30', '2023-10-31', '2023-11-30', '2023-12-31',
               '2024-01-31', '2024-02-29', '2024-03-31', '2024-04-30',
               '2024-05-31', '2024-06-30', '2024-07-31', '2024-08-31',
               '2024-09-30', '2024-10-31', '2024-11-30', '2024-12-31',
               '2025-01-31', '2025-02-28', '2025-03-31', '2025-04-30',
               '2025-05-31', '2025-06-30', '2025-07-31', '2025-08-31',
               '2025-09-30', '2025-10-31', '2025-11-30', '2025-12-31',
               '2026-01-31', '2026-02-28', '2026-03-31', '2026-04-30',
               '2026-05-31', '2026-06-30', '2026-07-31', '2026-08-31',
               '2026-09-30', '2026-10-31', '2026-11-30', '2026-12-31'],
              dtype='datetime64[ns]', freq='ME')

###### Creating a Yearly Date Range Using pd.date_range()

In [25]:
# pd.date_range() → Creates a sequence of dates.
# start → Starting date.
# end → Ending date.
# freq='YE' → Generates dates at the end of every year.

In [37]:
# Create a date range from 2021 to 2026
# with year-end frequency
date_rng = pd.date_range(
    start='2021-01-01',
    end='2026-12-31',
    freq='YE'
)
print(date_rng)

DatetimeIndex(['2021-12-31', '2022-12-31', '2023-12-31', '2024-12-31',
               '2025-12-31', '2026-12-31'],
              dtype='datetime64[ns]', freq='YE-DEC')

###### Selecting 1000 Random Dates from a Date Range

In [38]:
# np.random.choice() → Randomly selects values from an array.
# date_rng → Source date range from which dates are selected.
# size=1000 → Selects exactly 1000 dates.
# replace=True → Allows the same date to be selected multiple times.
# len(random_dates) → Checks the number of selected dates.

In [39]:
# Pick only 1000 random records from the date range
import numpy as np
random_dates = np.random.choice(
    date_rng,
    size=1000,
    replace=True
)
print(len(random_dates))

1000

###### Creating a Canteen DataFrame with Funny Names

In [40]:
# Creating DataFrame using random_dates
canteen_df = pd.DataFrame({ 
    'timestamp': pd.to_datetime(random_dates),   
    'order_id': np.arange(1, 1001),
    # Generate order IDs from 1 to 1000    
    'food_category': np.random.choice(
        ["Samosa Simba", "Puff Pichha", "Tea Thagubothu",
         "Choki Choki Rowdy", "Bajji Bujji"],
        size=1000
    ),   
    'price': np.random.randint(10, 500, size=1000),    
    'quantity': np.random.randint(1, 5, size=1000)
})
canteen_df

     timestamp  order_id      food_category  price  quantity
0   2022-12-31         1  Choki Choki Rowdy    121         1
1   2025-12-31         2        Bajji Bujji    184         4
2   2021-12-31         3        Bajji Bujji    111         2
3   2022-12-31         4        Puff Pichha    349         3
4   2021-12-31         5        Puff Pichha    300         3
..         ...       ...                ...    ...       ...
995 2021-12-31       996  Choki Choki Rowdy     86         3
996 2021-12-31       997       Samosa Simba    286         3
997 2021-12-31       998       Samosa Simba    313         1
998 2025-12-31       999     Tea Thagubothu    483         4
999 2024-12-31      1000       Samosa Simba    487         2

[1000 rows x 5 columns]