In [5]:
import pandas as pd
df = pd.read_excel(r"S:\DA  notes\Excel_data.xlsx")

###### Selecting Rows and Columns Using iloc

In [6]:
df.iloc[0:20, 0:5]
# 0:20 → Selects rows from position 0 to 19 (20 is excluded)
# 0:5  → Selects columns from position 0 to 4 (5 is excluded)
# iloc → Selects data using integer index positions

    ID       Name   Age         Profession  salary
0    1     olivia  23.0            Teacher  184518
1    2  sophia     20.0              Boxer  119572
2    3       jake  38.0          Scientist  174897
3    4      Rocky  56.0               Chef  117920
4    4      Rocky  56.0               Chef  117920
5    4      Rocky  56.0               Chef  117920
6    4      Rocky  56.0               Chef  117920
7    4      Rocky  56.0               Chef  117920
8    4      Rocky  56.0               Chef  117920
9    4      Rocky  56.0               Chef  117920
10  11      Rocky   NaN             Doctor   75543
11  12       Jake   NaN             Artist  174780
12  13     Olivia  22.0           Comedian  102063
13  14       John  46.0             Artist   43078
14  15       Jake  40.0               Chef  171553
15  16   Sherlock  30.0              Boxer   57774
16  17       Jake  46.0             Artist  135907
17  18       Jake  53.0  Software Engineer  127117
18  19      Rocky  25.0           Comedian  181312
19  20   Sherlock  40.0          Detective  118998

###### Selecting Rows and Columns Using iloc with Step

In [7]:
df.iloc[0:200:10,0:5:2]

      ID   Age  salary
0      1  23.0  184518
10    11   NaN   75543
20    21  40.0  118998
30    31  30.0   77599
40    41  52.0   46535
50    51  42.0  105830
60    61  37.0  106436
70    71  40.0  188182
80    81  38.0  125743
90    91  43.0   30407
100  101  60.0  163578
110  111  44.0  165346
120  121  43.0   34630
130  131  26.0  145227
140  141  46.0   61653
150  151  60.0  135857
160  161  42.0  150873
170  171  30.0  139649
180  181  32.0  134405
190  191  34.0  112912

###### Selecting Random Columns Using iloc

In [8]:
# iloc: Selecting specific columns using their index positions

df.iloc[0:200:10, [1, 4]]
# 0:200:10 → Selects rows from 0 to 199 with a step of 10
# [1, 4]    → Selects columns at positions 1 and 4

         Name  salary
0      olivia  184518
10      Rocky   75543
20   Sherlock  118998
30      Alice   77599
40      Alice   46535
50       Liam  105830
60   Sherlock  106436
70       Jake  188182
80       Emma  125743
90      Rocky   30407
100    Olivia  163578
110      John  165346
120  Mr. Bean   34630
130  Mr. Bean  145227
140      John   61653
150  Sherlock  135857
160     Rocky  150873
170  Mr. Bean  139649
180    Sophia  134405
190    Sophia  112912

###### Selecting Specific Columns Using iloc

In [9]:
df.iloc[1:10, [1,3,4]]

        Name   Profession  salary
1  sophia           Boxer  119572
2       jake    Scientist  174897
3      Rocky         Chef  117920
4      Rocky         Chef  117920
5      Rocky         Chef  117920
6      Rocky         Chef  117920
7      Rocky         Chef  117920
8      Rocky         Chef  117920
9      Rocky         Chef  117920

##### Selecting a Specific Value Using iloc

In [10]:
# iloc to get a specific value
print(df.iloc[1, 5])
# 1 → Selects the row at index position 1
# 5 → Selects the column at index position 5
# iloc → Uses integer index positions
# print() → Displays the selected value

2

###### Selecting Age and Salary Columns Using loc

In [11]:
# loc to get Age and Salary columns
df.loc[0:5, ["Age", "salary"]]
# 0:5 → Selects rows from index 0 to 5 (5 is included)
# ["Age", "salary"] → Selects only the Age and salary columns
# loc → Uses column names and index labels

    Age  salary
0  23.0  184518
1  20.0  119572
2  38.0  174897
3  56.0  117920
4  56.0  117920
5  56.0  117920

###### Using Comparison Conditions in loc

In [12]:
# Comparision condition inside the loc
df.Age > 50
# Checks which records have Age greater than 50
# Returns True or False for each row

0      False
1      False
2      False
3       True
4       True
       ...
495    False
496    False
497    False
498     True
499     True
Name: Age, Length: 500, dtype: bool

###### Filtering Data Using loc with a Condition

In [13]:
# Comparison condition inside the loc
df.loc[df.Age > 50, ["Age", "salary"]]
# Selects Age and salary of people whose age is greater than 50

      Age  salary
3    56.0  117920
4    56.0  117920
5    56.0  117920
6    56.0  117920
7    56.0  117920
..    ...     ...
489  56.0   41192
490  57.0  154180
492  55.0   57720
498  55.0  192618
499  59.0  194886

[126 rows x 2 columns]

###### Filtering Salary by Age Range

In [17]:
# Salary of people Age > 50 and Age < 70
df.loc[(df.Age > 50) & (df.Age < 70),["Age","salary"]]

      Age  salary
3    56.0  117920
4    56.0  117920
5    56.0  117920
6    56.0  117920
7    56.0  117920
..    ...     ...
489  56.0   41192
490  57.0  154180
492  55.0   57720
498  55.0  192618
499  59.0  194886

[126 rows x 2 columns]

###### Using iloc with a Boolean Condition

In [19]:
 # iloc does not work directly with a Pandas Series condition
# .values converts the Series into a NumPy array of True/False values
df.iloc[(df.Age > 50).values, 0:4]

      ID      Name   Age         Profession
3      4     Rocky  56.0               Chef
4      4     Rocky  56.0               Chef
5      4     Rocky  56.0               Chef
6      4     Rocky  56.0               Chef
7      4     Rocky  56.0               Chef
..   ...       ...   ...                ...
489  490      John  56.0          Scientist
490  491      John  57.0              Pilot
492  493      John  55.0             Artist
498  499    Olivia  55.0           Comedian
499  500  Sherlock  59.0  Software Engineer

[126 rows x 4 columns]

###### Checking the Type of Boolean Array

In [21]:
type((df.Age> 50).values)

numpy.ndarray

###### Updating Values in a DataFrame Using a Condition

In [22]:
###  Updating a value inside the dataframe
# replace / update all to age > 50  with 18
df[df.Age >50]

      ID      Name   Age         Profession  salary  Marriage_proposal_count
3      4     Rocky  56.0               Chef  117920                        2
4      4     Rocky  56.0               Chef  117920                        1
5      4     Rocky  56.0               Chef  117920                        3
6      4     Rocky  56.0               Chef  117920                       11
7      4     Rocky  56.0               Chef  117920                        2
..   ...       ...   ...                ...     ...                      ...
489  490      John  56.0          Scientist   41192                        7
490  491      John  57.0              Pilot  154180                        0
492  493      John  55.0             Artist   57720                        2
498  499    Olivia  55.0           Comedian  192618                        5
499  500  Sherlock  59.0  Software Engineer  194886                       28

[126 rows x 6 columns]

In [24]:
# Replace the Age with 18 for all people whose Age is greater than 50
df.loc[df.Age > 50, "Age"] = 18
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  18.0               Chef  117920                        2
4      4      Rocky  18.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  18.0           Comedian  192618                        5
499  500   Sherlock  18.0  Software Engineer  194886                       28

[500 rows x 6 columns]

###### Updating a Specific Value in a DataFrame Using loc

In [25]:
df.loc[0,"Name"] = "srujana"
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1    srujana  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  18.0               Chef  117920                        2
4      4      Rocky  18.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  18.0           Comedian  192618                        5
499  500   Sherlock  18.0  Software Engineer  194886                       28

[500 rows x 6 columns]

###### Updating a Specific Value Using iloc

In [27]:
# Update the value at row position 1 and column position 1
df.iloc[1, 1] = "Zombie"
# Display the updated DataFrame
df

      ID      Name   Age         Profession  salary  Marriage_proposal_count
0      1   srujana  23.0            Teacher  184518                        0
1      2    Zombie  20.0              Boxer  119572                        2
2      3      jake  38.0          Scientist  174897                        1
3      4     Rocky  18.0               Chef  117920                        2
4      4     Rocky  18.0               Chef  117920                        1
..   ...       ...   ...                ...     ...                      ...
495  496      John  45.0              Boxer  137929                        0
496  497  Sherlock  46.0              Boxer   39870                        6
497  498  Sherlock  47.0          Detective  165951                        5
498  499    Olivia  18.0           Comedian  192618                        5
499  500  Sherlock  18.0  Software Engineer  194886                       28

[500 rows x 6 columns]

###### Updating a Single Value Using at

In [28]:
### at & iat for single value access
# Update the Name at row label 2
df.at[2, "Name"] = "Ramesh"

# Display the updated DataFrame
df

      ID      Name   Age         Profession  salary  Marriage_proposal_count
0      1   srujana  23.0            Teacher  184518                        0
1      2    Zombie  20.0              Boxer  119572                        2
2      3    Ramesh  38.0          Scientist  174897                        1
3      4     Rocky  18.0               Chef  117920                        2
4      4     Rocky  18.0               Chef  117920                        1
..   ...       ...   ...                ...     ...                      ...
495  496      John  45.0              Boxer  137929                        0
496  497  Sherlock  46.0              Boxer   39870                        6
497  498  Sherlock  47.0          Detective  165951                        5
498  499    Olivia  18.0           Comedian  192618                        5
499  500  Sherlock  18.0  Software Engineer  194886                       28

[500 rows x 6 columns]

###### Updating a Single Value Using iat

In [29]:
# iat is used to access or update a single value using integer positions
# Update the value at row position 0 and column position 1
df.iat[0, 1] = "Vijay Deverakonda"
df

,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,1,Vijay Deverakonda,23.0,Teacher,184518,0
1,2,Zombie,20.0,Boxer,119572,2
2,3,Ramesh,38.0,Scientist,174897,1
3,4,Rocky,18.0,Chef,117920,2
4,4,Rocky,18.0,Chef,117920,1
...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929,0
496,497,Sherlock,46.0,Boxer,39870,6
497,498,Sherlock,47.0,Detective,165951,5
498,499,Olivia,18.0,Comedian,192618,5
499,500,Sherlock,18.0,Software Engineer,194886,28

###### Sorting Rows in a DataFrame

In [30]:
# Sort the DataFrame by Age in ascending order
df.sort_values("Age")

      ID      Name   Age         Profession  salary  Marriage_proposal_count
499  500  Sherlock  18.0  Software Engineer  194886                       28
316  317     Alice  18.0           Comedian  102420                        0
309  310      John  18.0  Software Engineer  175585                        5
297  298      Emma  18.0          Scientist  143154                        1
290  291     Rocky  18.0             Doctor  166138                        5
..   ...       ...   ...                ...     ...                      ...
46    47  Mr. Bean   NaN             Artist  190559                        5
71    72      Emma   NaN              Pilot   49986                        3
72    73    Sophia   NaN             Artist   86741                        1
73    74     Rocky   NaN  Software Engineer  159260                        0
74    75  Sherlock   NaN          Detective  165463                        0

[500 rows x 6 columns]

###### Sorting Rows by Name in Descending Order

In [31]:
# Sort the DataFrame by Name from Z to A
df.sort_values("Name", ascending=False)

,ID,Name,Age,Profession,salary,Marriage_proposal_count
1,2,Zombie,20.0,Boxer,119572,2
0,1,Vijay Deverakonda,23.0,Teacher,184518,0
338,339,Sophia,32.0,Detective,181192,0
405,406,Sophia,29.0,Artist,67411,8
72,73,Sophia,NaN,Artist,86741,1
...,...,...,...,...,...,...
408,409,Alice,18.0,Scientist,43963,4
363,364,Alice,25.0,Software Engineer,105197,10
316,317,Alice,18.0,Comedian,102420,0
359,360,Alice,36.0,Teacher,56591,0
28,29,Alice,21.0,Chef,84792,3

###### Storing Sorted DataFrame in a New Variable

In [32]:
# Sort the DataFrame by Name from Z to A and store it in df1
df1 = df.sort_values("Name", ascending=False)
# Display the sorted DataFrame
df1

,ID,Name,Age,Profession,salary,Marriage_proposal_count
1,2,Zombie,20.0,Boxer,119572,2
0,1,Vijay Deverakonda,23.0,Teacher,184518,0
338,339,Sophia,32.0,Detective,181192,0
405,406,Sophia,29.0,Artist,67411,8
72,73,Sophia,NaN,Artist,86741,1
...,...,...,...,...,...,...
408,409,Alice,18.0,Scientist,43963,4
363,364,Alice,25.0,Software Engineer,105197,10
316,317,Alice,18.0,Comedian,102420,0
359,360,Alice,36.0,Teacher,56591,0
28,29,Alice,21.0,Chef,84792,3

###### Sorting the Index of a DataFrame

In [33]:
# sort_index() is used to sort the index of the DataFrame
df1.sort_index()

,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,1,Vijay Deverakonda,23.0,Teacher,184518,0
1,2,Zombie,20.0,Boxer,119572,2
2,3,Ramesh,38.0,Scientist,174897,1
3,4,Rocky,18.0,Chef,117920,2
4,4,Rocky,18.0,Chef,117920,1
...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929,0
496,497,Sherlock,46.0,Boxer,39870,6
497,498,Sherlock,47.0,Detective,165951,5
498,499,Olivia,18.0,Comedian,192618,5
499,500,Sherlock,18.0,Software Engineer,194886,28

###### Sorting the Index In-Place

In [34]:
# Sort the index of df1 in ascending order and update df1 directly
df1.sort_index(inplace=True)
# Display the updated DataFrame
df1

,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,1,Vijay Deverakonda,23.0,Teacher,184518,0
1,2,Zombie,20.0,Boxer,119572,2
2,3,Ramesh,38.0,Scientist,174897,1
3,4,Rocky,18.0,Chef,117920,2
4,4,Rocky,18.0,Chef,117920,1
...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929,0
496,497,Sherlock,46.0,Boxer,39870,6
497,498,Sherlock,47.0,Detective,165951,5
498,499,Olivia,18.0,Comedian,192618,5
499,500,Sherlock,18.0,Software Engineer,194886,28

###### Setting a Column as the DataFrame Index

In [35]:
# Set the ID column as the index of the DataFrame
df1.set_index("ID", inplace=True)
# Display the updated DataFrame
df1

,Name,Age,Profession,salary,Marriage_proposal_count
ID,,,,,
1,Vijay Deverakonda,23.0,Teacher,184518,0
2,Zombie,20.0,Boxer,119572,2
3,Ramesh,38.0,Scientist,174897,1
4,Rocky,18.0,Chef,117920,2
4,Rocky,18.0,Chef,117920,1
...,...,...,...,...,...
496,John,45.0,Boxer,137929,0
497,Sherlock,46.0,Boxer,39870,6
498,Sherlock,47.0,Detective,165951,5
499,Olivia,18.0,Comedian,192618,5
500,Sherlock,18.0,Software Engineer,194886,28

###### Resetting the DataFrame Index

In [36]:
# Reset the index of the DataFrame
df1.reset_index(inplace=True)
# Display the updated DataFrame
df1

,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,1,Vijay Deverakonda,23.0,Teacher,184518,0
1,2,Zombie,20.0,Boxer,119572,2
2,3,Ramesh,38.0,Scientist,174897,1
3,4,Rocky,18.0,Chef,117920,2
4,4,Rocky,18.0,Chef,117920,1
...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929,0
496,497,Sherlock,46.0,Boxer,39870,6
497,498,Sherlock,47.0,Detective,165951,5
498,499,Olivia,18.0,Comedian,192618,5
499,500,Sherlock,18.0,Software Engineer,194886,28