In [1]:
import pandas as pd
df = pd.read_excel(r"S:\DA  notes\Excel_data.xlsx")
df.head()

   ID       Name   Age   Profession  salary  Marriage_proposal_count
0   1     olivia  23.0      Teacher  184518                        0
1   2  sophia     20.0        Boxer  119572                        2
2   3       jake  38.0    Scientist  174897                        1
3   4      Rocky  56.0         Chef  117920                        2
4   4      Rocky  56.0         Chef  117920                        1

###### Finding the Person with the Highest Salary

In [2]:
# Query: Find the person record who is getting the highest salary.
# Hint: max()
max(df.salary)

199529

###### Finding the Highest Salary Record Using max()

In [3]:
df[df.salary == df.salary.max()]

      ID      Name   Age   Profession  salary  Marriage_proposal_count
436  437  Sherlock  52.0        Boxer  199529                        3

###### Finding the Lowest Salary

In [33]:
# Query: Find the person record who is getting Lowest salary.
# Hint: min()

min(df.salary)

30164

###### Finding the Person with the Lowest Salary

In [34]:
df[df.salary == df.salary.min()]

      ID      Name   Age Profession  salary  Marriage_proposal_count
213  214  Sherlock  21.0       Chef   30164                        2

###### Checking Which Record Has the Lowest Salary

In [35]:
df.salary == df.salary.min()

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Name: salary, Length: 500, dtype: bool

###### Printing Name, Age, and Salary of the Highest-Paid Person

In [36]:
# Query: Print Name, Age, and Salary of the person having max salary
df[df.salary == df.salary.max()][['Name', 'Age', 'salary']]

         Name   Age  salary
436  Sherlock  52.0  199529

###### Selecting the Name Column

In [37]:
df.Name

0         olivia
1      sophia
2           jake
3          Rocky
4          Rocky
         ...
495         John
496     Sherlock
497     Sherlock
498       Olivia
499     Sherlock
Name: Name, Length: 500, dtype: object

###### Selecting the Name Column Using Bracket Notation

In [38]:
df["salary"]

0      184518
1      119572
2      174897
3      117920
4      117920
        ...
495    137929
496     39870
497    165951
498    192618
499    194886
Name: salary, Length: 500, dtype: int64

###### Selecting Multiple Columns Using []

In [39]:
df[["Name", "Age"]]

          Name   Age
0       olivia  23.0
1    sophia     20.0
2         jake  38.0
3        Rocky  56.0
4        Rocky  56.0
..         ...   ...
495       John  45.0
496   Sherlock  46.0
497   Sherlock  47.0
498     Olivia  55.0
499   Sherlock  59.0

[500 rows x 2 columns]

###### Selecting Multiple Columns in a Specific Order

In [40]:
df[["salary", "Age", "Name"]]

     salary   Age       Name
0    184518  23.0     olivia
1    119572  20.0  sophia
2    174897  38.0       jake
3    117920  56.0      Rocky
4    117920  56.0      Rocky
..      ...   ...        ...
495  137929  45.0       John
496   39870  46.0   Sherlock
497  165951  47.0   Sherlock
498  192618  55.0     Olivia
499  194886  59.0   Sherlock

[500 rows x 3 columns]

###### Filtering Data Using where()

In [41]:
 # where() is used for filtering the data
df1 = df.copy()                    # Creates a copy of the original DataFrame
df1 = df1.where(df1.Age > 50)      # Keeps values where Age is greater than 50;
                                   # other values are replaced with NaN [Missing/empty value.]
df1                                # Displays the filtered DataFrame

,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,Rocky,56.0,Chef,117920.0,2.0
4,4.0,Rocky,56.0,Chef,117920.0,1.0
...,...,...,...,...,...,...
495,NaN,NaN,NaN,NaN,NaN,NaN
496,NaN,NaN,NaN,NaN,NaN,NaN
497,NaN,NaN,NaN,NaN,NaN,NaN
498,499.0,Olivia,55.0,Comedian,192618.0,5.0
499,500.0,Sherlock,59.0,Software Engineer,194886.0,28.0

###### Filtering Records Without NaN Values

In [42]:
# Query: Filter records where Age is greater than 50
df[df.Age > 50]  # Returns only records where Age > 50; no NaN records are shown

      ID      Name   Age         Profession  salary  Marriage_proposal_count
3      4     Rocky  56.0               Chef  117920                        2
4      4     Rocky  56.0               Chef  117920                        1
5      4     Rocky  56.0               Chef  117920                        3
6      4     Rocky  56.0               Chef  117920                       11
7      4     Rocky  56.0               Chef  117920                        2
..   ...       ...   ...                ...     ...                      ...
489  490      John  56.0          Scientist   41192                        7
490  491      John  57.0              Pilot  154180                        0
492  493      John  55.0             Artist   57720                        2
498  499    Olivia  55.0           Comedian  192618                        5
499  500  Sherlock  59.0  Software Engineer  194886                       28

[126 rows x 6 columns]

###### Using where() to Filter Data

In [43]:
### where(): Used for filtering data
# where() returns NaN for values that don't satisfy the condition
df1 = df.copy()  
df1

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

###### Using where() with a Replacement Value

In [44]:
df1 = df.copy()  
df1 = df1.Age.where(df1.Age > 50,1) # Keeps Age if Age > 50; otherwise replaces it with 1
df1

0       1.0
1       1.0
2       1.0
3      56.0
4      56.0
       ...
495     1.0
496     1.0
497     1.0
498    55.0
499    59.0
Name: Age, Length: 500, dtype: float64

###### Indexing in Pandas Using loc and iloc

In [45]:
# Indexing: loc & iloc
# loc  → Label-based indexing
# iloc → Integer position-based indexing
# loc & iloc is used for filtering
# these helps to select particular ROW & Column in the dataframe

###### loc Indexer in Pandas

In [46]:
df.loc  # Used for label-based indexing

###### Selecting Rows and Columns Using loc

In [47]:
# Query: print records 1 to 4 and columns id, name, age only.
df.loc[1:4, 'ID': 'Age'] # df.loc[start_row : end_row, col_start: col_end]

   ID       Name   Age
1   2  sophia     20.0
2   3       jake  38.0
3   4      Rocky  56.0
4   4      Rocky  56.0

# Interview Question
Q: What is the difference between loc and iloc?
Ans:1. In loc columns are passed with their names but in iloccolumns are passed as index
2. iloc is easy to use due to index usage
3. iloc[start_ro: end_row-1, col_start : col_end-1]
4. iloc is little faster than the loc

###### Selecting Rows and Columns Using loc

In [48]:
# Query: Print records 10 to 40, and columns Name to Profession only.
df.loc[10:40, "Name":"Profession"]
# 10:40              → Selects rows 10 to 40 (40 is included)
# "Name":"Profession" → Selects columns from Name to Profession
# loc                 → Performs label-based indexing

        Name   Age         Profession
10     Rocky   NaN             Doctor
11      Jake   NaN             Artist
12    Olivia  22.0           Comedian
13      John  46.0             Artist
14      Jake  40.0               Chef
15  Sherlock  30.0              Boxer
16      Jake  46.0             Artist
17      Jake  53.0  Software Engineer
18     Rocky  25.0           Comedian
19  Sherlock  40.0          Detective
20  Sherlock  40.0          Detective
21      John  41.0          Scientist
22      John  41.0          Scientist
23  Sherlock  42.0              Boxer
24    Olivia  60.0          Detective
25    Olivia  53.0          Detective
26     Alice  48.0              Pilot
27  Sherlock  55.0          Scientist
28     Alice  21.0               Chef
29     Alice  21.0               Chef
30     Alice  30.0            Teacher
31    Olivia  30.0             Doctor
32  Mr. Bean  27.0             Artist
33    Olivia  45.0           Comedian
34  Sherlock  46.0               Chef
35  Mr. Bean  44.0           Comedian
36     Rocky  57.0            Teacher
37  Mr. Bean  32.0          Scientist
38      John  27.0  Software Engineer
39    Olivia  60.0  Software Engineer
40     Alice  52.0               Chef

###### Displaying All Column Names

In [49]:
df.columns

Index(['ID', 'Name', 'Age', 'Profession', 'salary', 'Marriage_proposal_count'], dtype='object')

In [50]:
# Query: Print records 1 to 4, and columns ID, Name, Age only.
df.iloc[1:5, 0:3]
# 1:5 → Selects rows at positions 1 to 4 (5 is excluded)
# 0:3 → Selects columns at positions 0 to 2 (3 is excluded)
# iloc → Uses integer index positions

   ID       Name   Age
1   2  sophia     20.0
2   3       jake  38.0
3   4      Rocky  56.0
4   4      Rocky  56.0