### 5. Handling of Missing Values (NaN/Null)

In [28]:
# Def : Null/NaN vlaues are missing values. Null is different from 0.
# IF their null values in the data the nwrong analysis will happen.
# Null/NaN values represent missing data in a DataFrame.
# Null/NaN is different from 0 because 0 is a valid value.
# Missing values can affect calculations and lead to incorrect analysis.
# We should identify missing values before performing data analysis.
# Pandas provides isnull(), notnull(), fillna(), and dropna() to handle missing values.

In [29]:
import pandas as pd
df = pd.read_excel(r"S:\DA  notes\Excel_data.xlsx")

###### Checking for Null / NaN Values

In [30]:
# Check for missing (Null/NaN) values in the DataFrame
df.isnull()

        ID   Name    Age  Profession  salary  Marriage_proposal_count
0    False  False  False       False   False                    False
1    False  False  False       False   False                    False
2    False  False  False       False   False                    False
3    False  False  False       False   False                    False
4    False  False  False       False   False                    False
..     ...    ...    ...         ...     ...                      ...
495  False  False  False       False   False                    False
496  False  False  False       False   False                    False
497  False  False  False       False   False                    False
498  False  False  False       False   False                    False
499  False  False  False       False   False                    False

[500 rows x 6 columns]

###### Counting Null / NaN Values in Each Column

In [31]:
#Check which column have how many null values
# Count the number of missing values in each column
# .sum() will say with column has the null values 
df.isnull().sum()

ID                         0
Name                       0
Age                        8
Profession                 0
salary                     0
Marriage_proposal_count    0
dtype: int64

###### Selecting Records with Null Values

In [32]:
# Select records where Age has a missing (NaN) value
df[df.Age.isnull()]

    ID      Name  Age         Profession  salary  Marriage_proposal_count
10  11     Rocky  NaN             Doctor   75543                        5
11  12      Jake  NaN             Artist  174780                        5
45  46      Liam  NaN             Doctor   84583                        0
46  47  Mr. Bean  NaN             Artist  190559                        5
71  72      Emma  NaN              Pilot   49986                        3
72  73    Sophia  NaN             Artist   86741                        1
73  74     Rocky  NaN  Software Engineer  159260                        0
74  75  Sherlock  NaN          Detective  165463                        0

###### Checking Null Values in the Age Column

In [33]:
# Check which values in the Age column are missing
df.Age.isnull()

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Name: Age, Length: 500, dtype: bool

###### Creating a Copy of a DataFrame

In [34]:
 # Create a copy of the DataFrame and store it in df1
df1 = df.copy()
# Display df1
df1

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

###### Removing Records with Null Values

In [35]:
# Remove rows that contain any Null/NaN values
# delete the records which is having null values
df1 = df1.dropna()
# Display the DataFrame after removing null values
df1

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[492 rows x 6 columns]

###### Checking the Shape of a DataFrame

In [36]:
df1.shape

(492, 6)

In [37]:
df2 = df.copy()
df2

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

###### Deleting Columns with Null Values

In [38]:
 # Remove columns that contain Null/NaN values
df2 = df2.dropna(axis=1)
df2

      ID       Name         Profession  salary  Marriage_proposal_count
0      1     olivia            Teacher  184518                        0
1      2  sophia                 Boxer  119572                        2
2      3       jake          Scientist  174897                        1
3      4      Rocky               Chef  117920                        2
4      4      Rocky               Chef  117920                        1
..   ...        ...                ...     ...                      ...
495  496       John              Boxer  137929                        0
496  497   Sherlock              Boxer   39870                        6
497  498   Sherlock          Detective  165951                        5
498  499     Olivia           Comedian  192618                        5
499  500   Sherlock  Software Engineer  194886                       28

[500 rows x 5 columns]

###### Remove Completely Empty Columns

In [39]:
# Remove columns only if all values in the column are Null/NaN
# how="all" - Deletes only if all values are NaN
df1.dropna(axis=1, how="all")

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[492 rows x 6 columns]

###### Removing Columns with Null / NaN Values

In [40]:
# Remove columns if they contain at least one Null/NaN value
df1.dropna(axis=1, how="any")

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[492 rows x 6 columns]

###### Replacing Null Values Using fillna()

In [41]:
# Create a copy of the original DataFrame
df3 = df.copy()
# Replace Null/NaN values in the Age column with 18
df3.Age = df3.Age.fillna(18)
# Check for remaining Null/NaN values
df3.isnull().sum()

ID                         0
Name                       0
Age                        0
Profession                 0
salary                     0
Marriage_proposal_count    0
dtype: int64

#### Finding and Handling Duplicate values

###### Checking Duplicate Records in a DataFrame

In [42]:
# Check for duplicate rows in the DataFrame
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Length: 500, dtype: bool

###### Counting Duplicate Records

In [43]:
# Count the total number of duplicate rows in the DataFrame
# Finding number of Duplicate records
df.duplicated().sum()

np.int64(3)

###### Showing Duplicate Records

In [44]:
 # Show the 2nd and subsequent duplicate records
# A row is duplicate when the complete record matches a previous row
df[df.duplicated()]

   ID   Name   Age Profession  salary  Marriage_proposal_count
7   4  Rocky  56.0       Chef  117920                        2
8   4  Rocky  56.0       Chef  117920                        2
9   4  Rocky  56.0       Chef  117920                        3

###### Showing All Duplicate Records

In [45]:
# Show all duplicate records, including the first occurrence
df[df.duplicated(keep=False)]

   ID   Name   Age Profession  salary  Marriage_proposal_count
3   4  Rocky  56.0       Chef  117920                        2
5   4  Rocky  56.0       Chef  117920                        3
7   4  Rocky  56.0       Chef  117920                        2
8   4  Rocky  56.0       Chef  117920                        2
9   4  Rocky  56.0       Chef  117920                        3

###### Finding Duplicates Based on Specific Columns

In [46]:
# Find duplicate records based on Name, Profession, and Salary
df[df.duplicated(subset=["Name", "Profession", "salary"])]

    ID      Name   Age Profession  salary  Marriage_proposal_count
4    4     Rocky  56.0       Chef  117920                        1
5    4     Rocky  56.0       Chef  117920                        3
6    4     Rocky  56.0       Chef  117920                       11
7    4     Rocky  56.0       Chef  117920                        2
8    4     Rocky  56.0       Chef  117920                        2
9    4     Rocky  56.0       Chef  117920                        3
20  21  Sherlock  40.0  Detective  118998                       13
22  23      John  41.0  Scientist  175925                        4
29  30     Alice  21.0       Chef   84792                        3

###### Counting Duplicate Records Based on Age and Salary

In [47]:
# Query : count all the records where age & Salary is matching /duplicate
# Count all records where both Age and salary are matching/duplicate
df[df.duplicated(keep=False, subset=["Age", "salary"])].count()

ID                         13
Name                       13
Age                        13
Profession                 13
salary                     13
Marriage_proposal_count    13
dtype: int64

###### Removing Duplicate Records

In [48]:
# Create a copy of the original DataFrame
df4 = df.copy()
# Remove duplicate rows
df4 = df4.drop_duplicates()
# Check the number of duplicate rows remaining
df4.duplicated().sum()

np.int64(0)

In [49]:
df4.shape

(497, 6)

###### Removing Duplicates Based on Specific Columns

In [50]:
df5 = df.copy()
# Remove duplicate records based on Age and salary
df5 = df5.drop_duplicates(subset=["Age", "salary"])
df5

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
10    11      Rocky   NaN             Doctor   75543                        5
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[491 rows x 6 columns]

In [51]:
df5.shape

(491, 6)

###### Counting Duplicates Based on Specific Columns

In [52]:
 # Count duplicate records based on Age and salary
df.duplicated(subset=["Age", "salary"]).sum()

np.int64(9)

#### Handling the inconsistant data

In [53]:
# Inconsistent data means values are stored in different or incorrect formats.
# Example: "Male", "male", "M" represent the same value in different forms.
# Inconsistent data can lead to incorrect analysis.
# We should identify and standardize inconsistent values before analysis.
# Common methods include replace(), map(), strip(), lower(), upper(), and astype().

###### Standardizing Column Names

In [54]:
# Make all column names start with a capital letter
df.columns = df.columns.str.title()
# Display the column names
df.columns

Index(['Id', 'Name', 'Age', 'Profession', 'Salary', 'Marriage_Proposal_Count'], dtype='object')

###### Finding Unique Values in the Name Column

In [55]:
# Find all unique values in the Name column
df.Name.unique()

array(['olivia', 'sophia   ', 'jake', 'Rocky', 'Jake', 'Olivia', 'John',
       'Sherlock', 'Alice', 'Mr. Bean', 'Sophia', 'Liam', 'Emma'],
      dtype=object)

###### Standardizing Name Values

In [56]:
# Convert all names to Title Case
df.Name = df.Name.str.title()
# Display unique names
df.Name.unique()

array(['Olivia', 'Sophia   ', 'Jake', 'Rocky', 'John', 'Sherlock',
       'Alice', 'Mr. Bean', 'Sophia', 'Liam', 'Emma'], dtype=object)

###### Removing Extra Spaces and Finding Unique Names

In [57]:
# Remove leading and trailing spaces from names
df.Name = df.Name.str.strip()
df.Name.unique()

array(['Olivia', 'Sophia', 'Jake', 'Rocky', 'John', 'Sherlock', 'Alice',
       'Mr. Bean', 'Liam', 'Emma'], dtype=object)

In [58]:
df.Profession.unique()

array(['Teacher', '      Boxer', 'Scientist', 'Chef', 'Doctor', 'Artist',
       'Comedian', 'Software Engineer', 'Detective', 'Pilot'],
      dtype=object)

In [60]:
df.Profession = df.Profession.str.strip()
df.Profession.unique()

array(['Teacher', 'Boxer', 'Scientist', 'Chef', 'Doctor', 'Artist',
       'Comedian', 'Software Engineer', 'Detective', 'Pilot'],
      dtype=object)

#### Data Transformation Using apply() and map()

In [61]:
# apply() applies a function to values in a Series or along rows/columns of a DataFrame.
# map() transforms values in a Pandas Series.
# apply() can work with custom functions and built-in functions.
# map() is commonly used for value mapping and replacement.
# Both are useful for cleaning and transforming data.

###### Doubling the Salary of Employees Using apply()

In [62]:
# Query: Double the salary of the employees
df6 = df.copy()
# Double the salary of each employee
df6.Salary = df6.Salary.apply(lambda x: x * 2)
df6

      Id      Name   Age         Profession  Salary  Marriage_Proposal_Count
0      1    Olivia  23.0            Teacher  369036                        0
1      2    Sophia  20.0              Boxer  239144                        2
2      3      Jake  38.0          Scientist  349794                        1
3      4     Rocky  56.0               Chef  235840                        2
4      4     Rocky  56.0               Chef  235840                        1
..   ...       ...   ...                ...     ...                      ...
495  496      John  45.0              Boxer  275858                        0
496  497  Sherlock  46.0              Boxer   79740                        6
497  498  Sherlock  47.0          Detective  331902                        5
498  499    Olivia  55.0           Comedian  385236                        5
499  500  Sherlock  59.0  Software Engineer  389772                       28

[500 rows x 6 columns]

###### Creating a Senior/Junior Column Using apply()

In [63]:
# Query: Create a new column which divide the employees as senior and junior
# based upon the salary. if salary >300000 :senior otherwise junior
# use of apply(0 on complete dataframe
# Create a new Position column based on Salary
df6["Position"] = df6.apply(
    lambda row: "Senior" if row["Salary"] > 300000 else "Junior",
    axis=1
)
df6

,Id,Name,Age,Profession,Salary,Marriage_Proposal_Count,Position
0,1,Olivia,23.0,Teacher,369036,0,Senior
1,2,Sophia,20.0,Boxer,239144,2,Junior
2,3,Jake,38.0,Scientist,349794,1,Senior
3,4,Rocky,56.0,Chef,235840,2,Junior
4,4,Rocky,56.0,Chef,235840,1,Junior
...,...,...,...,...,...,...,...
495,496,John,45.0,Boxer,275858,0,Junior
496,497,Sherlock,46.0,Boxer,79740,6,Junior
497,498,Sherlock,47.0,Detective,331902,5,Senior
498,499,Olivia,55.0,Comedian,385236,5,Senior
499,500,Sherlock,59.0,Software Engineer,389772,28,Senior

###### Categorizing Employees as Old or Young Using apply()

In [64]:
# Create a new category column based on Age
df6["category"] = df6.apply(
    lambda row: "Old" if row["Age"] > 40 else "Young",
    axis=1
)
df6

,Id,Name,Age,Profession,Salary,Marriage_Proposal_Count,Position,category
0,1,Olivia,23.0,Teacher,369036,0,Senior,Young
1,2,Sophia,20.0,Boxer,239144,2,Junior,Young
2,3,Jake,38.0,Scientist,349794,1,Senior,Young
3,4,Rocky,56.0,Chef,235840,2,Junior,Old
4,4,Rocky,56.0,Chef,235840,1,Junior,Old
...,...,...,...,...,...,...,...,...
495,496,John,45.0,Boxer,275858,0,Junior,Old
496,497,Sherlock,46.0,Boxer,79740,6,Junior,Old
497,498,Sherlock,47.0,Detective,331902,5,Senior,Old
498,499,Olivia,55.0,Comedian,385236,5,Senior,Old
499,500,Sherlock,59.0,Software Engineer,389772,28,Senior,Old