###### 2. Data input and output(SQL, JSON)

In [5]:
 import pandas as pd

In [7]:
# Import excel file as a Dataframe
df = pd.read_excel("Excel_data.xlsx")
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

###### Reading and Writing in a SQL Table Using Python

In [8]:
# Reading and writing in a sql table 
import sqlite3
# creating a database if it dont exist
conn = sqlite3.connect("profession.db")

###### Creating a Table and Storing DataFrame Data in SQL

In [11]:
# creating a table and storing the dataframe data inside it
df.to_sql("prof_table", conn, if_exists = "replace")

500

###### Reading Data from SQL Table into a DataFrame

In [12]:
#reading the data from sql table to df
df = pd.read_sql("Select * from prof_table", conn)
df

,index,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,0,1,olivia,23.0,Teacher,184518,0
1,1,2,sophia,20.0,Boxer,119572,2
2,2,3,jake,38.0,Scientist,174897,1
3,3,4,Rocky,56.0,Chef,117920,2
4,4,4,Rocky,56.0,Chef,117920,1
...,...,...,...,...,...,...,...
495,495,496,John,45.0,Boxer,137929,0
496,496,497,Sherlock,46.0,Boxer,39870,6
497,497,498,Sherlock,47.0,Detective,165951,5
498,498,499,Olivia,55.0,Comedian,192618,5
499,499,500,Sherlock,59.0,Software Engineer,194886,28

###### How to import the JSON file

In [14]:
 # Importing data from JSON
df_json = pd.read_json("json_data.json")

df_json

,order_id,customer_name,food_item,delivery_boy,rating,delivery_time_min
0,101,Ramu,Idli Burger,Speed Shankar,5,15
1,102,Priya,Dosa Pizza,Late Laxman,2,60
2,103,Dinesh,Paneer Sambar,Turbo Thambi,4,25
3,104,Lachu,Mango Maggi,Round Robin,1,90
4,105,Meena,Coconut Coffee,Careless Kannan,3,40

In [15]:
# Exporting data from datafram to json file
df_json.to_json("foodData_DA22.json")

###### 3.Understanding the Dataset(Head,Tail, dType...)

In [17]:
import pandas as pd
df = pd.read_excel("Excel_data.xlsx")
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

###### How to use Head() and Tail()

In [22]:
# view the data with head() , tail() functions
# head(x) function is used for accessing top X records
import pandas as pd
df = pd.read_excel("Excel_data.xlsx")
df.head(6)

   ID       Name   Age   Profession  salary  Marriage_proposal_count
0   1     olivia  23.0      Teacher  184518                        0
1   2  sophia     20.0        Boxer  119572                        2
2   3       jake  38.0    Scientist  174897                        1
3   4      Rocky  56.0         Chef  117920                        2
4   4      Rocky  56.0         Chef  117920                        1
5   4      Rocky  56.0         Chef  117920                        3

In [21]:
# head() function by default shows the records
import pandas as pd
df = pd.read_excel("Excel_data.xlsx")
df.head()

   ID       Name   Age   Profession  salary  Marriage_proposal_count
0   1     olivia  23.0      Teacher  184518                        0
1   2  sophia     20.0        Boxer  119572                        2
2   3       jake  38.0    Scientist  174897                        1
3   4      Rocky  56.0         Chef  117920                        2
4   4      Rocky  56.0         Chef  117920                        1

In [26]:
# displaying the last 5 rows of the DataFrame
df.tail()

      ID      Name   Age         Profession  salary  Marriage_proposal_count
495  496      John  45.0              Boxer  137929                        0
496  497  Sherlock  46.0              Boxer   39870                        6
497  498  Sherlock  47.0          Detective  165951                        5
498  499    Olivia  55.0           Comedian  192618                        5
499  500  Sherlock  59.0  Software Engineer  194886                       28

###### Heading: Checking the Shape of the DataFrame

In [27]:
# displaying the number of rows and columns
df.shape

(500, 6)

###### how to see single column

In [23]:
#show the single column
df['Age']

0      23.0
1      20.0
2      38.0
3      56.0
4      56.0
       ...
495    45.0
496    46.0
497    47.0
498    55.0
499    59.0
Name: Age, Length: 500, dtype: float64

In [24]:
## other way to print the single column
df.salary

0      184518
1      119572
2      174897
3      117920
4      117920
        ...
495    137929
496     39870
497    165951
498    192618
499    194886
Name: salary, Length: 500, dtype: int64

In [28]:
# printing the two columns name
df[["Name","Marriage_proposal_count"]]

          Name  Marriage_proposal_count
0       olivia                        0
1    sophia                           2
2         jake                        1
3        Rocky                        2
4        Rocky                        1
..         ...                      ...
495       John                        0
496   Sherlock                        6
497   Sherlock                        5
498     Olivia                        5
499   Sherlock                       28

[500 rows x 2 columns]

In [30]:
# printing multiple columns
df[["Name","Profession","salary"]]

          Name         Profession  salary
0       olivia            Teacher  184518
1    sophia                 Boxer  119572
2         jake          Scientist  174897
3        Rocky               Chef  117920
4        Rocky               Chef  117920
..         ...                ...     ...
495       John              Boxer  137929
496   Sherlock              Boxer   39870
497   Sherlock          Detective  165951
498     Olivia           Comedian  192618
499   Sherlock  Software Engineer  194886

[500 rows x 3 columns]

In [31]:
# renaming the column names
df_rename = df.rename(columns = {'Name' : 'Peru', 'Profession' : 'Vruthi'})
df_rename

      ID       Peru   Age             Vruthi  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

###### Displaying All Column Names

In [33]:
# print all the column names
df_rename.columns

Index(['ID', 'Peru', 'Age', 'Vruthi', 'salary', 'Marriage_proposal_count'], dtype='object')

###### Creating a new column in the dataframe

In [34]:
# HEre, rank() function is a pandas function
# rank() function is giving rank-1 to minimum salary and higher rank value to higher salary 
df['rank'] = df['salary'].rank()
df

,ID,Name,Age,Profession,salary,Marriage_proposal_count,rank
0,1,olivia,23.0,Teacher,184518,0,462.0
1,2,sophia,20.0,Boxer,119572,2,267.0
2,3,jake,38.0,Scientist,174897,1,426.0
3,4,Rocky,56.0,Chef,117920,2,251.0
4,4,Rocky,56.0,Chef,117920,1,251.0
...,...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929,0,320.0
496,497,Sherlock,46.0,Boxer,39870,6,36.0
497,498,Sherlock,47.0,Detective,165951,5,395.0
498,499,Olivia,55.0,Comedian,192618,5,480.0
499,500,Sherlock,59.0,Software Engineer,194886,28,487.0

###### Creating a New Column from an Existing Column

In [40]:
 df['rank123'] = df['rank']

###### Ranking Salaries and Sorting by Rank

In [41]:
df['rank'] = df['salary'].rank()
df.sort_values('rank')
# sort_values () is used for sorting the dataframe based upon a column value

,ID,Name,Age,Profession,salary,Marriage_proposal_count,rank,rank123
213,214,Sherlock,21.0,Chef,30164,2,1.0,1.0
90,91,Rocky,43.0,Software Engineer,30407,10,2.0,2.0
398,399,Rocky,25.0,Scientist,30659,5,3.0,3.0
329,330,Sherlock,40.0,Scientist,30905,0,4.0,4.0
284,285,Jake,46.0,Detective,30971,1,5.0,5.0
...,...,...,...,...,...,...,...,...
474,475,Sophia,30.0,Doctor,198653,1,496.0,496.0
167,168,Mr. Bean,44.0,Comedian,198847,14,497.0,497.0
132,133,Rocky,31.0,Doctor,198978,8,498.0,498.0
65,66,Emma,57.0,Pilot,199317,1,499.0,499.0
436,437,Sherlock,52.0,Boxer,199529,3,500.0,500.0

###### Ranking Salaries in Descending Order

In [42]:
df['rank'] = df['salary'].rank(ascending = False)
df.sort_values('rank')

,ID,Name,Age,Profession,salary,Marriage_proposal_count,rank,rank123
436,437,Sherlock,52.0,Boxer,199529,3,1.0,500.0
65,66,Emma,57.0,Pilot,199317,1,2.0,499.0
132,133,Rocky,31.0,Doctor,198978,8,3.0,498.0
167,168,Mr. Bean,44.0,Comedian,198847,14,4.0,497.0
474,475,Sophia,30.0,Doctor,198653,1,5.0,496.0
...,...,...,...,...,...,...,...,...
284,285,Jake,46.0,Detective,30971,1,496.0,5.0
329,330,Sherlock,40.0,Scientist,30905,0,497.0,4.0
398,399,Rocky,25.0,Scientist,30659,5,498.0,3.0
90,91,Rocky,43.0,Software Engineer,30407,10,499.0,2.0
213,214,Sherlock,21.0,Chef,30164,2,500.0,1.0

###### Dropping Columns from the DataFrame

In [44]:
# Dropping the columns
# axis = 1: delete the column
# axis = 0: delete the row

df.drop(['rank', 'rank123'], axis=1)

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]