##### DataFrame(2nd array)

In [1]:
# Data frame is a 2D array, store data in form of matrix.

##### Creating DataFrame

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame()     # it creates empty dataframe
print(df)

Empty DataFrame
Columns: []
Index: []

###### How to convert list to Data frame

In [4]:
# convert list to dataframe
subjects = ["Maths", "English", "Computer", "Accounts"]

df = pd.DataFrame(subjects)
print(df)

          0
0     Maths
1   English
2  Computer
3  Accounts

###### we Have given Column name

In [6]:
# convert list to dataframe - we have added a column 
mobile_list = ["Samsung", "iPhone", "OnePlus", "Vivo"]

df = pd.DataFrame(mobile_list, columns=["Mobile Brand"])

print(df)

  Mobile Brand
0      Samsung
1       iPhone
2      OnePlus
3         Vivo

###### We Have created a 2D array

In [7]:
# convert list to dataframe
cities_list = ["Hyderabad", "Delhi", "Mumbai", "Chennai"]
df = pd.DataFrame(cities_list, columns=["City Name"])
df

   City Name
0  Hyderabad
1      Delhi
2     Mumbai
3    Chennai

###### How to add name and value to 2D Array

In [8]:
# list of list 
books_list = [
    ["Harry Potter", 500],
    ["The Alchemist", 300],
    ["Wings of Fire", 450],
    ["Atomic Habits", 600]
]
df = pd.DataFrame(books_list, columns=["Book Name", "Price"])
df

       Book Name  Price
0   Harry Potter    500
1  The Alchemist    300
2  Wings of Fire    450
3  Atomic Habits    600

###### How to add 3 columns in the 2D array

In [9]:
grocery_list = [
    ["Rice", 5, 300],
    ["Sugar", 2, 100],
    ["Oil", 3, 450],
    ["Dal", 4, 400]
]
df = pd.DataFrame(
    grocery_list,
    columns=["Item", "Quantity", "Price"]
)
df

    Item  Quantity  Price
0   Rice         5    300
1  Sugar         2    100
2    Oil         3    450
3    Dal         4    400

###### Converting List of Tuples to DataFrame

In [10]:
# Converting list of tuples to DataFrame
students_list = [
    ("Ravi", 20, "B.Com", 85),
    ("Priya", 21, "B.Com", 92),
    ("Arjun", 20, "B.Com", 78),
    ("Sneha", 22, "B.Com", 88)
]
df = pd.DataFrame(
    students_list,
    columns=["Name", "Age", "Course", "Marks"]
)
df

    Name  Age Course  Marks
0   Ravi   20  B.Com     85
1  Priya   21  B.Com     92
2  Arjun   20  B.Com     78
3  Sneha   22  B.Com     88

###### Converting Set of Tuples into DataFrame

In [11]:
# Converting set of tuples into DataFrame
players_set = {
    ("Virat", 250, 12000),
    ("Rohit", 260, 11000),
    ("Rahul", 180, 7000),
    ("Hardik", 150, 4000)
}
df = pd.DataFrame(
    players_set,
    columns=["Player", "Matches", "Runs"]
)
df

   Player  Matches   Runs
0   Rohit      260  11000
1  Hardik      150   4000
2   Rahul      180   7000
3   Virat      250  12000

###### Creating DataFrame from Set of Set

In [12]:
# creating DataFrame from set of set
# we can not create the dataframe from set of set.
# because, set is mutable.
# in set, we cann't store the mutable items.
# in set, we can only store immutable items.

fruits_list = {
    {"AratiPandu",40,100},
    {"MamidiPandu",1000,200},
    {"KamalaPandu",10,1000},
    {"DrakshaPandu",300,-100}
}
df = pd.DataFrame(
    fruits_list,
    columns=["Fruits Name", "Price", "Discount"]
)
df

TypeError: unhashable type: 'set'

###### Creating the DataFrame from Dictionary

In [13]:
# Creating DataFrame from Dictionary
student_data = {
    "Name": ["Shiva", "Niranjan", "Suresh", "Akash", "Lahari", "Rakesh"],
    "Salary": [40, 50, 60, 15, 25, 100]
}
df1 = pd.DataFrame(student_data)
df1

       Name  Salary
0     Shiva      40
1  Niranjan      50
2    Suresh      60
3     Akash      15
4    Lahari      25
5    Rakesh     100

In [14]:
student_data = {
    "Name": ["Rahul", "Akash", "Vindu", "Uma", "Priya", "Kiran"],
    "Salary": [40, 50, 60, 15, 25, 100],
    "Study_time": [12, 14, 16, 1, 5, 24]
}
df1 = pd.DataFrame(student_data)
df1

    Name  Salary  Study_time
0  Rahul      40          12
1  Akash      50          14
2  Vindu      60          16
3    Uma      15           1
4  Priya      25           5
5  Kiran     100          24

#### 2. Data input and output(CSV, EXCEL, SQL, JSON)

In [15]:
# importing data from CSV file
import os 
os.getcwd()

'C:\\Users\\admin\\ DA  notes'

In [16]:
os.chdir(r"S:\DA")

In [17]:
os.getcwd()

'S:\\DA'

In [18]:
# import a csv file as dataFrame
df_csv = pd.read_csv("CSV_data.csv")
df

   Player  Matches   Runs
0   Rohit      260  11000
1  Hardik      150   4000
2   Rahul      180   7000
3   Virat      250  12000