In [3]:
import pandas as pd
df = pd.read_excel(r"S:\DA  notes\Excel_data.xlsx")

###### Creating a New Column Using apply() with Multiple Columns

In [4]:
# Example-1: Apply() function
# Query: Create a new column which is having salary/age
# Motive: use of apply() function on complete dataframe and access multiple columns
# Create a copy of the DataFrame
df1 = df.copy()
# Create a new column by dividing Salary by Age
df1["Salary_Per_Year_age"] = df1.apply(
    lambda row: row["salary"] / row["Age"],
    axis=1
)
df1

,ID,Name,Age,Profession,salary,Marriage_proposal_count,Salary_Per_Year_age
0,1,olivia,23.0,Teacher,184518,0,8022.521739
1,2,sophia,20.0,Boxer,119572,2,5978.600000
2,3,jake,38.0,Scientist,174897,1,4602.552632
3,4,Rocky,56.0,Chef,117920,2,2105.714286
4,4,Rocky,56.0,Chef,117920,1,2105.714286
...,...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929,0,3065.088889
496,497,Sherlock,46.0,Boxer,39870,6,866.739130
497,498,Sherlock,47.0,Detective,165951,5,3530.872340
498,499,Olivia,55.0,Comedian,192618,5,3502.145455
499,500,Sherlock,59.0,Software Engineer,194886,28,3303.152542

##### Data Transformation Using map()

In [5]:
# map() performs element-wise transformation on a Pandas Series.
# It applies a function to each individual value.
# map() is mainly used with Series, not directly with the complete DataFrame.
# map() can be used with lambda functions.
# map() can also be used with a dictionary to replace/map values.
# It is useful for data cleaning, transformation, and value replacement.

###### Example 1: Converting Names to Uppercase Using map()

In [6]:
# Definition:
# map() is used for element-wise transformation, similar to apply()
df2 = df.copy()
# Convert all names to uppercase
df2.Name = df2.Name.map(lambda val: str(val).upper())
df2

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     OLIVIA  23.0            Teacher  184518                        0
1      2  SOPHIA     20.0              Boxer  119572                        2
2      3       JAKE  38.0          Scientist  174897                        1
3      4      ROCKY  56.0               Chef  117920                        2
4      4      ROCKY  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       JOHN  45.0              Boxer  137929                        0
496  497   SHERLOCK  46.0              Boxer   39870                        6
497  498   SHERLOCK  47.0          Detective  165951                        5
498  499     OLIVIA  55.0           Comedian  192618                        5
499  500   SHERLOCK  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

###### Example 2: Converting Professions from English to Telugu Using map()

In [7]:
# Display all unique professions
df.Profession.unique()

array(['Teacher', '      Boxer', 'Scientist', 'Chef', 'Doctor', 'Artist',
       'Comedian', 'Software Engineer', 'Detective', 'Pilot'],
      dtype=object)

###### Example 2: Mapping Professions to Funny Telugu-Style Names

In [8]:
profession_map = {
    'Teacher': 'Saarr',                    
    '      Boxer': 'Pedhi',                      
    'Scientist': 'Sastravettu',            
    'Chef': 'Vantavaadu',                  
    'Doctor': 'Vaidhyudu',                 
    'Artist': 'Kalakaarudu',               
    'Comedian': 'Haasyagadu',              
    'Software Engineer': 'Kulodu',         
    'Detective': 'Guptachari',            
    'Pilot': 'Gaalodu'                     
}

df2['Prof_telugu'] = df2.Profession.map(profession_map)

df2

,ID,Name,Age,Profession,salary,Marriage_proposal_count,Prof_telugu
0,1,OLIVIA,23.0,Teacher,184518,0,Saarr
1,2,SOPHIA,20.0,Boxer,119572,2,Pedhi
2,3,JAKE,38.0,Scientist,174897,1,Sastravettu
3,4,ROCKY,56.0,Chef,117920,2,Vantavaadu
4,4,ROCKY,56.0,Chef,117920,1,Vantavaadu
...,...,...,...,...,...,...,...
495,496,JOHN,45.0,Boxer,137929,0,Pedhi
496,497,SHERLOCK,46.0,Boxer,39870,6,Pedhi
497,498,SHERLOCK,47.0,Detective,165951,5,Guptachari
498,499,OLIVIA,55.0,Comedian,192618,5,Haasyagadu
499,500,SHERLOCK,59.0,Software Engineer,194886,28,Kulodu

### 9. Aggregation and Grouping

###### Displaying DataFrame Information

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       500 non-null    int64
 1   Name                     500 non-null    object
 2   Age                      492 non-null    float64
 3   Profession               500 non-null    object
 4   salary                   500 non-null    int64
 5   Marriage_proposal_count  500 non-null    int64
dtypes: float64(1), int64(3), object(2)
memory usage: 23.6+ KB

###### Calculating the Total Salary

In [10]:
# Total salary
df.salary.sum()

np.int64(57801414)

###### Calculating the Average Salary

In [11]:
# Average salary
df.salary.mean()

np.float64(115602.828)

###### Calculating the Median Salary

In [12]:
# Median of salary
# Middle value after sorting the data
# Example: 10, 20, 30, 40, 50, 60, 70, 80

df.salary.median()

117920.0

###### Finding the Most Frequent Profession

In [13]:
# mode() : Most frequent data
df.Profession.mode()

0    Chef
Name: Profession, dtype: object

###### Finding the Minimum Salary

In [14]:
# Minimum salary
df.salary.min()

30164

###### Counting Records in Each Category

In [15]:
# value_counts() : Number of records related to each category
df.Profession.value_counts()

Profession
Chef                 58
Scientist            54
      Boxer          53
Pilot                53
Comedian             52
Software Engineer    51
Doctor               48
Teacher              45
Detective            45
Artist               41
Name: count, dtype: int64

###### Counting Non-Null Values

In [16]:
# count() : Count the non-null values
df.count()

ID                         500
Name                       500
Age                        492
Profession                 500
salary                     500
Marriage_proposal_count    500
dtype: int64

###### Counting Null / Missing Values

In [18]:
# Count the null (missing) values in each column
df.isnull().sum()

ID                         0
Name                       0
Age                        8
Profession                 0
salary                     0
Marriage_proposal_count    0
dtype: int64

###### Grouping Data by Profession and Counting Records

In [17]:
# groupby() : Group the data based on category
df.groupby('Profession').Name.count()

Profession
      Boxer          53
Artist               41
Chef                 58
Comedian             52
Detective            45
Doctor               48
Pilot                53
Scientist            54
Software Engineer    51
Teacher              45
Name: Name, dtype: int64

###### Calculating Average Salary by Profession

In [20]:
# Find average salary based on profession
df.groupby('Profession').salary.mean()

Profession
      Boxer          103895.867925
Artist               124550.756098
Chef                 110806.620690
Comedian             122689.000000
Detective            120964.977778
Doctor               113964.333333
Pilot                108641.471698
Scientist            126669.481481
Software Engineer    117908.941176
Teacher              107922.711111
Name: salary, dtype: float64

###### Calculating Average Salary by Age

In [18]:
# Find average salary based upon age
df.groupby('Age').salary.mean()

Age
20.0    107930.300000
21.0    111202.666667
22.0    123330.000000
23.0    106353.875000
24.0     96071.000000
25.0    118117.956522
26.0    105049.545455
27.0    121657.000000
28.0    115759.727273
29.0    106755.333333
30.0    126964.785714
31.0    142756.833333
32.0    126444.230769
33.0    130019.428571
34.0    114673.000000
35.0     78758.000000
36.0    124278.777778
37.0    113419.230769
38.0    137063.000000
39.0    103876.769231
40.0    108059.400000
41.0    120925.900000
42.0    106310.411765
43.0     94403.111111
44.0    126647.916667
45.0    127032.428571
46.0     96160.705882
47.0    106546.000000
48.0    113052.785714
49.0    117906.090909
50.0    130377.857143
51.0    115272.333333
52.0    141711.333333
53.0     99333.500000
54.0    129167.846154
55.0    122092.700000
56.0     97167.714286
57.0    125854.052632
58.0    111681.090909
59.0    115163.000000
60.0    114066.666667
Name: salary, dtype: float64

###### Applying Multiple Aggregate Functions Using agg()

In [19]:
# agg() : Apply multiple aggregate functions together on data
df[["Age", "salary"]].agg(["mean", "sum"])

               Age        salary
mean     40.810976  1.156028e+05
sum   20079.000000  5.780141e+07

###### Applying Multiple Aggregate Functions Using agg()

In [21]:
# Apply multiple aggregate functions
df[["Age", "salary"]].agg(["mean", "sum", "max", "min"])

               Age        salary
mean     40.810976  1.156028e+05
sum   20079.000000  5.780141e+07
max      60.000000  1.995290e+05
min      20.000000  3.016400e+04

###### Applying Different Aggregate Functions to Different Columns

In [22]:
# Apply different aggregate functions on different columns
df.agg({
    "Age": ["min", "max"],
    "salary": ["mean", "min"]
})

       Age      salary
min   20.0   30164.000
max   60.0         NaN
mean   NaN  115602.828

###### Combining groupby() and agg()

In [23]:
# groupby() + agg()
df.groupby("Profession").agg({
    "Age": ["min", "max"],
    "salary": ["mean", "min"]
})

                    Age               salary
                    min   max           mean    min
Profession
      Boxer        20.0  58.0  103895.867925  30976
Artist             20.0  60.0  124550.756098  32961
Chef               20.0  60.0  110806.620690  30164
Comedian           20.0  60.0  122689.000000  32354
Detective          20.0  60.0  120964.977778  30971
Doctor             22.0  60.0  113964.333333  31209
Pilot              20.0  60.0  108641.471698  31129
Scientist          22.0  60.0  126669.481481  30659
Software Engineer  21.0  60.0  117908.941176  30407
Teacher            20.0  60.0  107922.711111  31162