In [9]:
import pandas as pd

df = pd.read_excel(r"S:\DA  notes\Excel_data.xlsx")

df.head()

   ID       Name   Age   Profession  salary  Marriage_proposal_count
0   1     olivia  23.0      Teacher  184518                        0
1   2  sophia     20.0        Boxer  119572                        2
2   3       jake  38.0    Scientist  174897                        1
3   4      Rocky  56.0         Chef  117920                        2
4   4      Rocky  56.0         Chef  117920                        1

### Replace a value in data frame

In [10]:
df['Name'] = df.Name.replace("Olivia", "Niranjan")
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499   Niranjan  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [11]:
df['Name'] = df.Name.replace("olivia","Rakul")
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1      Rakul  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499   Niranjan  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

###### Replacing Multiple Values in Pandas

In [12]:
 # Replacing multiple values together
df['Name'] = df.Name.replace({"Rakul": "Sujitha", "Raja": "Srujana"})

# Replacing values from multiple columns together
# inplace = True : performs the task without creating a new DataFrame
df.replace({"Raja": "Srujana", "Teacher": "Upadhaye"}, inplace=True)

df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1    Sujitha  23.0           Upadhaye  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499   Niranjan  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

###### Checking Data Types of Columns in Pandas

In [13]:
# dtypes is used to check the data type of all columns
# In Pandas, strings are represented as object
df.dtypes

ID                           int64
Name                        object
Age                        float64
Profession                  object
salary                       int64
Marriage_proposal_count      int64
dtype: object

###### Converting Data Types in Pandas

In [14]:
# Convert the data type of a column
df['Name'] = df['Name'].astype("string")
# Check the data types
df.dtypes

ID                                  int64
Name                       string[python]
Age                               float64
Profession                         object
salary                              int64
Marriage_proposal_count             int64
dtype: object

###### Converting a Column to Float Data Type

In [16]:
# Convert the salary column to float data type
df['salary'] = df['salary'].astype("float")
# Check the data types
df.dtypes

ID                                  int64
Name                       string[python]
Age                               float64
Profession                         object
salary                            float64
Marriage_proposal_count             int64
dtype: object

###### Selecting Columns Based on Data Types

In [17]:
# Printing columns having specific data types
df.select_dtypes(include=['int64', 'float64'])

      ID   Age    salary  Marriage_proposal_count
0      1  23.0  184518.0                        0
1      2  20.0  119572.0                        2
2      3  38.0  174897.0                        1
3      4  56.0  117920.0                        2
4      4  56.0  117920.0                        1
..   ...   ...       ...                      ...
495  496  45.0  137929.0                        0
496  497  46.0   39870.0                        6
497  498  47.0  165951.0                        5
498  499  55.0  192618.0                        5
499  500  59.0  194886.0                       28

[500 rows x 4 columns]

###### Selecting Object and String Columns

In [18]:
# Selecting columns with object or string data types
df.select_dtypes(include=['object', 'string']).columns

Index(['Name', 'Profession'], dtype='object')

###### Displaying DataFrame Information

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       500 non-null    int64
 1   Name                     500 non-null    string
 2   Age                      492 non-null    float64
 3   Profession               500 non-null    object
 4   salary                   500 non-null    float64
 5   Marriage_proposal_count  500 non-null    int64
dtypes: float64(2), int64(2), object(1), string(1)
memory usage: 23.6+ KB

###### Finding Unique Values in a Column

In [20]:
# Query: Print all the unique professions
df.Profession.unique()

array(['Upadhaye', '      Boxer', 'Scientist', 'Chef', 'Doctor', 'Artist',
       'Comedian', 'Software Engineer', 'Detective', 'Pilot'],
      dtype=object)

###### Counting Unique Values in a Column

In [21]:
# nunique() tells the number of unique values
df.Profession.nunique()

10

###### Counting the Frequency of Unique Values

In [22]:
# Query: How many people are Boxers in this dataset
df.Profession.value_counts()

Profession
Chef                 58
Scientist            54
      Boxer          53
Pilot                53
Comedian             52
Software Engineer    51
Doctor               48
Upadhaye             45
Detective            45
Artist               41
Name: count, dtype: int64

###### Descriptive Statistics of the DataFrame

In [23]:
# describe() is used to get detailed statistical information about the data
df.describe()

               ID         Age         salary  Marriage_proposal_count
count  500.000000  492.000000     500.000000                500.00000
mean   250.458000   40.810976  115602.828000                  4.02600
std    144.552978   11.790553   49404.366846                  5.25362
min      1.000000   20.000000   30164.000000                  0.00000
25%    125.750000   31.000000   74964.750000                  1.00000
50%    250.500000   40.500000  117920.000000                  3.00000
75%    375.250000   51.000000  160579.500000                  5.00000
max    500.000000   60.000000  199529.000000                 40.00000

###### Descriptive Statistics for String/Object Columns

In [24]:
# Describing the string/object columns
df.describe(include=["object", "string"])

            Name Profession
count        500        500
unique        13         10
top     Sherlock       Chef
freq          61         58

### Data filtering and indexing (loc,iloc,where())

###### Filtering Records Based on Salary

In [25]:
# Query: Filter all the records where salary > 100000
df.salary > 100000

0       True
1       True
2       True
3       True
4       True
       ...
495     True
496    False
497     True
498     True
499     True
Name: salary, Length: 500, dtype: bool

###### Filtering DataFrame Records Using a Condition

In [26]:
# Query: Filter all the records where salary > 100000
df[df.salary > 100000]

,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,1,Sujitha,23.0,Upadhaye,184518.0,0
1,2,sophia,20.0,Boxer,119572.0,2
2,3,jake,38.0,Scientist,174897.0,1
3,4,Rocky,56.0,Chef,117920.0,2
4,4,Rocky,56.0,Chef,117920.0,1
...,...,...,...,...,...,...
493,494,Sophia,39.0,Doctor,174500.0,0
495,496,John,45.0,Boxer,137929.0,0
497,498,Sherlock,47.0,Detective,165951.0,5
498,499,Niranjan,55.0,Comedian,192618.0,5
499,500,Sherlock,59.0,Software Engineer,194886.0,28

###### Filtering Data Using Multiple Conditions

In [27]:
# Query: Filter all the records where salary > 100000 and salary < 150000

df[(df.salary > 100000) & (df.salary < 150000)]

,ID,Name,Age,Profession,salary,Marriage_proposal_count
1,2,sophia,20.0,Boxer,119572.0,2
3,4,Rocky,56.0,Chef,117920.0,2
4,4,Rocky,56.0,Chef,117920.0,1
5,4,Rocky,56.0,Chef,117920.0,3
6,4,Rocky,56.0,Chef,117920.0,11
...,...,...,...,...,...,...
469,470,Sophia,42.0,Software Engineer,102357.0,0
480,481,Sherlock,22.0,Detective,126604.0,0
483,484,Niranjan,59.0,Artist,124648.0,2
491,492,Emma,34.0,Artist,145412.0,1
495,496,John,45.0,Boxer,137929.0,0

###### Filtering Records Within a Salary Range

In [29]:
# Query: Filter all the records where salary > 100000 and salary < 150000

df[(df.salary > 100000) & (df.salary < 150000)]

,ID,Name,Age,Profession,salary,Marriage_proposal_count
1,2,sophia,20.0,Boxer,119572.0,2
3,4,Rocky,56.0,Chef,117920.0,2
4,4,Rocky,56.0,Chef,117920.0,1
5,4,Rocky,56.0,Chef,117920.0,3
6,4,Rocky,56.0,Chef,117920.0,11
...,...,...,...,...,...,...
469,470,Sophia,42.0,Software Engineer,102357.0,0
480,481,Sherlock,22.0,Detective,126604.0,0
483,484,Niranjan,59.0,Artist,124648.0,2
491,492,Emma,34.0,Artist,145412.0,1
495,496,John,45.0,Boxer,137929.0,0

###### Filtering Records Using OR Condition

In [30]:
# Query: Filter all the records where salary < 100000 OR salary > 150000

df[(df.salary < 100000) | (df.salary > 150000)]

      ID      Name   Age         Profession    salary  Marriage_proposal_count
0      1   Sujitha  23.0           Upadhaye  184518.0                        0
2      3      jake  38.0          Scientist  174897.0                        1
10    11     Rocky   NaN             Doctor   75543.0                        5
11    12      Jake   NaN             Artist  174780.0                        5
13    14      John  46.0             Artist   43078.0                       12
..   ...       ...   ...                ...       ...                      ...
494  495     Rocky  27.0             Doctor   46975.0                        0
496  497  Sherlock  46.0              Boxer   39870.0                        6
497  498  Sherlock  47.0          Detective  165951.0                        5
498  499  Niranjan  55.0           Comedian  192618.0                        5
499  500  Sherlock  59.0  Software Engineer  194886.0                       28

[349 rows x 6 columns]